name: Scrape male character

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 12 */2 * *"

jobs:
  start_scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run : npm install
    - name: Start scrape data of male character
      run : npm run scrape:male
    - name: Commit and push if it changed
      run: |-
        git config user.name "satyawikananda"
        git config user.email "${{ secrets.EMAIL }}"
        git add -A
        timestamp=$(date -u)
        git commit -m "chore(scrape): Update scrape data of male character" || exit 0
        git push
